Comparition

# NumPy - Int32 - have fixed type, less bytes of memory, uses continuous memory
# Lists - pointers to objects, not using continous memory

In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [6]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
b.ndim
b.shape
b.dtype

dtype('int64')

Assigning changing specific rows and columns

In [11]:
a = np.array([[1,2,3,4,5,6,7,8],[9,10,11,12,13,14,15,16]])
print(a)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]


In [15]:
a[1,5]


14

In [16]:
a[0,:]


array([1, 2, 3, 4, 5, 6, 7, 8])

In [18]:
a[:,2]


array([ 3, 11])

In [19]:
a[0, 1:6:2]

array([2, 4, 6])

In [22]:
a[1,5] = 20
print(a)

# zmiana wartosci w kolumnie
a[:,2] = 5
print(a)

a[:,2] = [8,8]
print(a)


[[ 1  2  5  4  5  6  7  8]
 [ 9 10  5 12 13 20 15 16]]
[[ 1  2  5  4  5  6  7  8]
 [ 9 10  5 12 13 20 15 16]]
[[ 1  2  8  4  5  6  7  8]
 [ 9 10  8 12 13 20 15 16]]


In [24]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [26]:
print(b[0,1,1])
b[:,1,:]

4


array([[3, 4],
       [7, 8]])

In [28]:
b[:,1,:] = 13
print(b)

[[[ 1  2]
  [13 13]]

 [[ 5  6]
  [13 13]]]


Initializing different types of arrays

In [29]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [30]:
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [32]:
np.full((2,2), 80, dtype='float32')

array([[80., 80.],
       [80., 80.]], dtype=float32)

In [38]:
np.random.rand(2,2,3)
np.random.random_sample(b.shape)

array([[[0.28378912, 0.3859159 ],
        [0.51022508, 0.65209622]],

       [[0.32132085, 0.07027209],
        [0.74555819, 0.27257408]]])

In [41]:
np.random.randint(7, size=(3,3))

array([[2, 0, 5],
       [3, 2, 6],
       [6, 2, 0]])

In [46]:
arr = np.array([1,2,3])
r1 = np.repeat(arr,3, axis=0)
print(r1)

arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)



[1 1 1 2 2 2 3 3 3]
[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [53]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


be carefull when copying arrays - a = b nie kopiuje
b = a.copy() jest ok

Math

In [54]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [56]:
a + 2

array([5, 6, 7, 8])

In [57]:
np.cos(a)

array([-0.9899925 , -0.65364362,  0.28366219,  0.96017029])

# Linear algebra

In [61]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)
np.matmul(b,a)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.]])

In [63]:
c = np.identity(3)
np.linalg.det(c)

1.0